# Generated by Django 4.0.4 on 2022-06-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('creationDate', models.DateField()),
                ('beenRead', models.BooleanField()),
            ],
        ),
    ]
